import { TypedEvent, TypedEventBase } from "../events/EventBase";
import { CanvasTypes, Context2D } from "../html/canvas";
export interface PaddingRect {
    top: number;
    right: number;
    bottom: number;
    left: number;
}
interface TextImageEvents {
    redrawn: TypedEvent<"redrawn">;
    notready: TypedEvent<"notready">;
}
export interface TextImageOptions {
    minWidth: number;
    maxWidth: number;
    minHeight: number;
    maxHeight: number;
    strokeColor: string;
    strokeSize: number;
    bgColor: string;
    value: string;
    scale: number;
    fillColor: string;
    textDirection: string;
    wrapWords: boolean;
    fontStyle: string;
    fontVariant: string;
    fontWeight: string;
    fontFamily: string;
    fontSize: number;
    padding: PaddingRect;
}
export declare class TextImage extends TypedEventBase<TextImageEvents> {
    private _minWidth;
    private _maxWidth;
    private _minHeight;
    private _maxHeight;
    private _strokeColor;
    private _strokeSize;
    private _bgColor;
    private _value;
    private _scale;
    private _fillColor;
    private _textDirection;
    private _wrapWords;
    private _fontStyle;
    private _fontVariant;
    private _fontWeight;
    private _fontFamily;
    private _fontSize;
    private _padding;
    private _canvas;
    private _g;
    constructor(options?: Partial<TextImageOptions>);
    get scale(): number;
    set scale(v: number);
    get minWidth(): number;
    set minWidth(v: number);
    get maxWidth(): number;
    set maxWidth(v: number);
    get minHeight(): number;
    set minHeight(v: number);
    get maxHeight(): number;
    set maxHeight(v: number);
    get canvas(): CanvasTypes;
    get width(): number;
    get height(): number;
    get padding(): PaddingRect;
    set padding(v: PaddingRect);
    get wrapWords(): boolean;
    set wrapWords(v: boolean);
    get textDirection(): string;
    set textDirection(v: string);
    get fontStyle(): string;
    set fontStyle(v: string);
    get fontVariant(): string;
    set fontVariant(v: string);
    get fontWeight(): string;
    set fontWeight(v: string);
    get fontSize(): number;
    set fontSize(v: number);
    get fontFamily(): string;
    set fontFamily(v: string);
    get fillColor(): string;
    set fillColor(v: string);
    get strokeColor(): string;
    set strokeColor(v: string);
    get strokeSize(): number;
    set strokeSize(v: number);
    get bgColor(): string;
    set bgColor(v: string);
    get value(): string;
    set value(v: string);
    draw(g: Context2D, x: number, y: number): void;
    private split;
    private redraw;
}
export {};
