export interface IInputBinding {
    keyButtonUp: string;
    keyButtonDown: string;
    keyButtonLeft: string;
    keyButtonRight: string;
    keyButtonEmote: string;
    keyButtonToggleAudio: string;
    keyButtonZoomOut: string;
    keyButtonZoomIn: string;
    gpButtonEmote: number;
    gpButtonToggleAudio: number;
    gpButtonZoomIn: number;
    gpButtonZoomOut: number;
    gpButtonUp: number;
    gpButtonDown: number;
    gpButtonLeft: number;
    gpButtonRight: number;
    [v: string]: string | number;
}
export declare class Settings {
    private _drawHearing;
    private _audioDistanceMin;
    private _audioDistanceMax;
    private _audioRolloff;
    private _fontSize;
    private _transitionSpeed;
    private _zoom;
    private _roomName;
    private _userName;
    private _email;
    private _avatarEmoji;
    private _avatarURL;
    private _gamepadIndex;
    private _preferredAudioOutputID;
    private _preferredAudioInputID;
    private _preferredVideoInputID;
    private _inputBinding;
    constructor();
    private commit;
    get preferredAudioOutputID(): string;
    set preferredAudioOutputID(value: string);
    get preferredAudioInputID(): string;
    set preferredAudioInputID(value: string);
    get preferredVideoInputID(): string;
    set preferredVideoInputID(value: string);
    get transitionSpeed(): number;
    set transitionSpeed(value: number);
    get drawHearing(): boolean;
    set drawHearing(value: boolean);
    get audioDistanceMin(): number;
    set audioDistanceMin(value: number);
    get audioDistanceMax(): number;
    set audioDistanceMax(value: number);
    get audioRolloff(): number;
    set audioRolloff(value: number);
    get fontSize(): number;
    set fontSize(value: number);
    get zoom(): number;
    set zoom(value: number);
    get userName(): string;
    set userName(value: string);
    get email(): string;
    set email(value: string);
    get avatarEmoji(): string;
    set avatarEmoji(value: string);
    get avatarURL(): string;
    set avatarURL(value: string);
    get roomName(): string;
    set roomName(value: string);
    get gamepadIndex(): number;
    set gamepadIndex(value: number);
    get inputBinding(): IInputBinding;
    set inputBinding(value: IInputBinding);
}
