import { dice } from "./dice";
import { EmojiGroup } from "./EmojiGroup";

export const allIcons = new EmojiGroup(
    "All Icons", "All Icons", 
    //faces,
    //love,
    //cartoon,
    //hands,
    //bodyParts,
    //people,
    //gestures,
    //inMotion,
    //resting,
    //roles,
    //fantasy,
    //animals,
    //plants,
    //food,
    //flags,
    //vehicles,
    //clocks,
    //arrows,
    //shapes,
    //buttons,
    //zodiac,
    //chess,
    dice,
    //math,
    //games,
    //sportsEquipment,
    //clothing,
    //town,
    //music,
    //weather,
    //astro,
    //finance,
    //writing,
    //science,
    //tech,
    //mail,
    //celebration,
    //tools,
    //office,
    //signs,
    //religion,
    //household,
    //activities,
    //travel,
    //medieval
);
