import { EmojiGroup } from "./EmojiGroup";
import { clearButton, coolButton, freeButton, idButton, newButton, ngButton, okButton, sosButton, upButton, vsButton, radioButton, backArrow, endArrow, onArrow, soonArrow, topArrow, checkBoxWithCheck, inputLatinUppercase, inputLatinLowercase, inputNumbers, inputSymbols, inputLatinLetters, shuffleTracksButton, repeatButton, repeatSingleButton, upwardsButton, downwardsButton, playButton, pauseButton, reverseButton, ejectButton, fastForwardButton, fastReverseButton, fastUpButton, fastDownButton, nextTrackButton, lastTrackButton, playOrPauseButton, stopButton, recordButton } from "./emojis";

export const buttons = new EmojiGroup(
    "Buttons", "Buttons",
    clearButton,
    coolButton,
    freeButton,
    idButton,
    newButton,
    ngButton,
    okButton,
    sosButton,
    upButton,
    vsButton,
    radioButton,
    backArrow,
    endArrow,
    onArrow,
    soonArrow,
    topArrow,
    checkBoxWithCheck,
    inputLatinUppercase,
    inputLatinLowercase,
    inputNumbers,
    inputSymbols,
    inputLatinLetters,
    shuffleTracksButton,
    repeatButton,
    repeatSingleButton,
    upwardsButton,
    downwardsButton,
    playButton,
    pauseButton,
    reverseButton,
    ejectButton,
    fastForwardButton,
    fastReverseButton,
    fastUpButton,
    fastDownButton,
    nextTrackButton,
    lastTrackButton,
    playOrPauseButton,
    pauseButton,
    stopButton,
    recordButton);
