import { EmojiGroup } from "./EmojiGroup";
import { coolButton, freeButton, newButton, upButton, vsButton, radioButton, backArrow, endArrow, onArrow, soonArrow, topArrow, checkBoxWithCheck, inputLatinUppercase, inputLatinLowercase, inputNumbers, inputSymbols, inputLatinLetters, shuffleTracksButton, repeatButton, repeatSingleButton, upwardsButton, downwardsButton, playButton, pauseButton, reverseButton, ejectButton, fastForwardButton, fastReverseButton, fastUpButton, fastDownButton, nextTrackButton, lastTrackButton, playOrPauseButton, stopButton, recordButton, cLButton, iDButton, nGButton, oKButton, sOSButton } from "./emojis";

export const buttons = new EmojiGroup(
    "Buttons", "Buttons",
    cLButton,
    coolButton,
    freeButton,
    iDButton,
    newButton,
    nGButton,
    oKButton,
    sOSButton,
    upButton,
    vsButton,
    radioButton,
    backArrow,
    endArrow,
    onArrow,
    soonArrow,
    topArrow,
    checkBoxWithCheck,
    inputLatinUppercase,
    inputLatinLowercase,
    inputNumbers,
    inputSymbols,
    inputLatinLetters,
    shuffleTracksButton,
    repeatButton,
    repeatSingleButton,
    upwardsButton,
    downwardsButton,
    playButton,
    pauseButton,
    reverseButton,
    ejectButton,
    fastForwardButton,
    fastReverseButton,
    fastUpButton,
    fastDownButton,
    nextTrackButton,
    lastTrackButton,
    playOrPauseButton,
    pauseButton,
    stopButton,
    recordButton);
