export declare const whiteChessPieces: import("./EmojiGroup").EmojiGroup;
export declare const blackChessPieces: import("./EmojiGroup").EmojiGroup;
export declare const chessPawns: import("./EmojiGroup").EmojiGroup;
export declare const chessRooks: import("./EmojiGroup").EmojiGroup;
export declare const chessBishops: import("./EmojiGroup").EmojiGroup;
export declare const chessKnights: import("./EmojiGroup").EmojiGroup;
export declare const chessQueens: import("./EmojiGroup").EmojiGroup;
export declare const chessKings: import("./EmojiGroup").EmojiGroup;
export declare const chess: import("./EmojiGroup").EmojiGroup;
