import { EmojiGroup } from "./EmojiGroup";
import { oneOClock, twoOClock, threeOClock, fourOClock, fiveOClock, sixOClock, sevenOClock, eightOClock, nineOClock, tenOClock, elevenOClock, twelveOClock, oneThirty, twoThirty, threeThirty, fourThirty, fiveThirty, sixThirty, sevenThirty, eightThirty, nineThirty, tenThirty, elevenThirty, twelveThirty, mantelpieceClock, watch, alarmClock, stopwatch, timerClock, hourglassDone, hourglassNotDone } from "./emojis";


export const clocks = new EmojiGroup(
    "Clocks", "Time-keeping pieces",
    oneOClock,
    twoOClock,
    threeOClock,
    fourOClock,
    fiveOClock,
    sixOClock,
    sevenOClock,
    eightOClock,
    nineOClock,
    tenOClock,
    elevenOClock,
    twelveOClock,
    oneThirty,
    twoThirty,
    threeThirty,
    fourThirty,
    fiveThirty,
    sixThirty,
    sevenThirty,
    eightThirty,
    nineThirty,
    tenThirty,
    elevenThirty,
    twelveThirty,
    mantelpieceClock,
    watch,
    alarmClock,
    stopwatch,
    timerClock,
    hourglassDone,
    hourglassNotDone);
