import { EmojiGroup } from "./EmojiGroup";
import { fileFolder, openFileFolder, pageWithCurl, pageFacingUp, calendar, tearOffCalendar, cardIndex, cardIndexDividers, cardFileBox, fileCabinet, wastebasket, spiralNotePad, spiralCalendar, chartIncreasing, chartDecreasing, barChart, clipboard, pushpin, roundPushpin, paperclip, linkedPaperclips, straightRuler, triangularRuler, bookmarkTabs, ledger, notebook, notebookWithDecorativeCover, closedBook, openBook, greenBook, blueBook, orangeBook, books, nameBadge, scroll, memo, scissors, envelope } from "./emojis";


export const office = new EmojiGroup(
    "Office", "Office",
    fileFolder,
    openFileFolder,
    pageWithCurl,
    pageFacingUp,
    calendar,
    tearOffCalendar,
    cardIndex,
    cardIndexDividers,
    cardFileBox,
    fileCabinet,
    wastebasket,
    spiralNotePad,
    spiralCalendar,
    chartIncreasing,
    chartDecreasing,
    barChart,
    clipboard,
    pushpin,
    roundPushpin,
    paperclip,
    linkedPaperclips,
    straightRuler,
    triangularRuler,
    bookmarkTabs,
    ledger,
    notebook,
    notebookWithDecorativeCover,
    closedBook,
    openBook,
    greenBook,
    blueBook,
    orangeBook,
    books,
    nameBadge,
    scroll,
    memo,
    scissors,
    envelope);
