import { EmojiGroup } from "./EmojiGroup";
import { cinema, noMobilePhone, noOneUnderEighteen, prohibited, cigarette, noSmoking, litterInBinSign, noLittering, potableWater, nonPotableWater, noBicycles, noPedestrians, childrenCrossing, mensRoom, womensRoom, restroom, babySymbol, waterCloset, passportControl, customs, baggageClaim, leftLuggage, parkingButton, wheelchairSymbol, radioactive, biohazard, warning, highVoltage, noEntry, recyclingSymbol, female, male, transgender } from "./emojis";


export const signs = new EmojiGroup(
    "Signs", "Signs",
    cinema,
    noMobilePhone,
    noOneUnderEighteen,
    prohibited,
    cigarette,
    noSmoking,
    litterInBinSign,
    noLittering,
    potableWater,
    nonPotableWater,
    noBicycles,
    noPedestrians,
    childrenCrossing,
    mensRoom,
    womensRoom,
    restroom,
    babySymbol,
    waterCloset,
    passportControl,
    customs,
    baggageClaim,
    leftLuggage,
    parkingButton,
    wheelchairSymbol,
    radioactive,
    biohazard,
    warning,
    highVoltage,
    noEntry,
    recyclingSymbol,
    female,
    male,
    transgender);
