import { EmojiGroup } from "./EmojiGroup";
import { buildingConstruction, houses, cityscape, derelictHouse, classicalBuilding, desert, desertIsland, nationalPark, stadium, house, houseWithGarden, officeBuilding, japanesePostOffice, postOffice, hospital, bank, aTMSign, hotel, loveHotel, convenienceStore, school, departmentStore, factory, bridgeAtNight, fountain, shoppingBags, receipt, shoppingCart, barberPole, wedding, ballotBoxWithBallot } from "./emojis";


export const town = new EmojiGroup(
    "Town", "Town",
    buildingConstruction,
    houses,
    cityscape,
    derelictHouse,
    classicalBuilding,
    desert,
    desertIsland,
    nationalPark,
    stadium,
    house,
    houseWithGarden,
    officeBuilding,
    japanesePostOffice,
    postOffice,
    hospital,
    bank,
    aTMSign,
    hotel,
    loveHotel,
    convenienceStore,
    school,
    departmentStore,
    factory,
    bridgeAtNight,
    fountain,
    shoppingBags,
    receipt,
    shoppingCart,
    barberPole,
    wedding,
    ballotBoxWithBallot);
