import { EmojiGroup } from "./EmojiGroup";
import { sunriseOverMountains, sunrise, cityscapeAtDusk, sunset, nightWithStars, closedUmbrella, umbrella, umbrellaWithRainDrops, snowman, snowmanWithoutSnow, sun, cloud, sunBehindSmallCloud, sunBehindCloud, sunBehindLargeCloud, sunBehindRainCloud, cloudWithRain, cloudWithSnow, cloudWithLightning, cloudWithLightningAndRain, snowflake, cyclone, tornado, windFace, waterWave, fog, foggy, rainbow, thermometer } from "./emojis";

export const weather = new EmojiGroup(
    "Weather", "Weather",
    sunriseOverMountains,
    sunrise,
    cityscapeAtDusk,
    sunset,
    nightWithStars,
    closedUmbrella,
    umbrella,
    umbrellaWithRainDrops,
    snowman,
    snowmanWithoutSnow,
    sun,
    cloud,
    sunBehindSmallCloud,
    sunBehindCloud,
    sunBehindLargeCloud,
    sunBehindRainCloud,
    cloudWithRain,
    cloudWithSnow,
    cloudWithLightning,
    cloudWithLightningAndRain,
    snowflake,
    cyclone,
    tornado,
    windFace,
    waterWave,
    fog,
    foggy,
    rainbow,
    thermometer);
